In [7]:
import pandas as pd

In [8]:
df_vendas = pd.read_excel('../data/dados_ecommerce.xlsx', sheet_name='vendas_olist')

In [9]:
df_vendas['produto_categoria'] = df_vendas['produto_categoria'].fillna('Não Informado')

In [10]:
df_vendas['cliente_cidade'] = df_vendas['cliente_cidade'].fillna('Desconhecido')

In [11]:
df_vendas = df_vendas.dropna(subset=['preco'])

In [12]:
df_vendas.isna().sum()

id_pedido            0
data_compra          0
produto_categoria    0
preco                0
frete                0
cliente_cidade       0
avaliacao_score      0
dtype: int64

In [13]:
df_vendas.groupby('produto_categoria')["preco"].sum()

produto_categoria
Não Informado              968.13
beleza_saude              7890.66
esporte_lazer             3700.17
informatica_acessorios    7482.96
moveis_decoracao          4006.52
utilidades_domesticas     7574.36
Name: preco, dtype: float64

In [14]:
faturamente_categoria=df_vendas.groupby('produto_categoria')["preco"].sum().sort_values(ascending=False)

In [19]:
faturamento_caterogia = faturamente_categoria
faturamento_caterogia

produto_categoria
beleza_saude              7890.66
utilidades_domesticas     7574.36
informatica_acessorios    7482.96
moveis_decoracao          4006.52
esporte_lazer             3700.17
Não Informado              968.13
Name: preco, dtype: float64

In [16]:
df_vendas.groupby('produto_categoria')['preco'].agg(['sum','mean','count']).sort_values(by='sum',ascending=False)

                            sum        mean  count
produto_categoria
beleza_saude            7890.66  151.743462     52
utilidades_domesticas   7574.36  120.227937     63
informatica_acessorios  7482.96  143.903077     52
moveis_decoracao        4006.52  114.472000     35
esporte_lazer           3700.17  137.043333     27
Não Informado            968.13   88.011818     11

In [17]:
analise_vendas = df_vendas.groupby('produto_categoria')['preco'].agg(['sum','mean','count']).sort_values(by='sum',ascending=False)

In [21]:
analise_cidade = df_vendas.groupby('cliente_cidade')['preco'].agg(['sum','count']).sort_values(by='sum', ascending=False)
analise_cidade

                     sum  count
cliente_cidade
sao paulo       12795.33     79
rio de janeiro   7441.43     58
Desconhecido     3600.56     27
belo horizonte   2559.44     23
curitiba         2486.31     25
porto alegre     1570.85     15
salvador         1168.88     13